// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundPattern: typeof import('./src/components/globals/BackgroundPattern.vue')['default']
    DarkToggle: typeof import('./src/components/globals/DarkToggle.vue')['default']
    Header: typeof import('./src/components/blocks/Header.vue')['default']
    IconCodiconGithubInverted: typeof import('~icons/codicon/github-inverted')['default']
    IconHeroiconsOutlineCheckCircle: typeof import('~icons/heroicons-outline/check-circle')['default']
    IconHeroiconsOutlineColorSwatch: typeof import('~icons/heroicons-outline/color-swatch')['default']
    IconMdiArch: typeof import('~icons/mdi/arch')['default']
    IconMdiGithub: typeof import('~icons/mdi/github')['default']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    MetamaskConnect: typeof import('./src/components/globals/MetamaskConnect.vue')['default']
    SampleWalletData: typeof import('./src/components/cards/SampleWalletData.vue')['default']
    TerminalCommand: typeof import('./src/components/terminal/TerminalCommand.vue')['default']
    TerminalDevData: typeof import('./src/components/terminal/TerminalDevData.vue')['default']
    TerminalHeader: typeof import('./src/components/terminal/TerminalHeader.vue')['default']
    TerminalShell: typeof import('./src/components/terminal/TerminalShell.vue')['default']
    TerminalTitlebar: typeof import('./src/components/terminal/TerminalTitlebar.vue')['default']
    TerminalWindow: typeof import('./src/components/terminal/TerminalWindow.vue')['default']
    ThemePicker: typeof import('./src/components/globals/ThemePicker.vue')['default']
  }
}

export { }
